---
title: "10-01-logistic"
format: pdf
editor: visual
---

## Ch 10: Logistic Regression

Logistic regression is one of methods of classification, which is used when the outcome variable is binary. In this case, mlr can give us predictions where the predicted probability could be less than 0 or greater than 1.

The logistic regression will result in predicted probabilities to be between 0 and 1.

After using the `glm()` function, logistic regression is implemented in \`caret\`. \`caret\` is basically a machine learning environment which is a wrapper for more than 60 individual r packages and aims to provide a common framework for implementing these algorithms using a unifying syntax. Though \`caret\` was introduced earlier, here we develop a basic understanding of the syntax and this can be used to fit a variety of machine learning models. Specifically, we will cover the following topics:

1\. Use of the \`trainControl()\` function.

1\. Carry out a k-fold cross validation approach (note logistic regression with use the \`createDataPartition()\` function.)

1\. Use of the \`preProcess()\` function in the training set, if any.

1\. Use cross validation to find the best model.

1\. Search for a less complex model using various tolerance values.

Note:To install all the libraries needed by \`caret\` upfront, use the command:

\`install.packages("caret", dependencies = c("Depends", "Suggests"))\`
